import {CareerProps} from '../types/careers'

export const CAREERS: CareerProps[] = [
  {
    position: 'Full Stack Engineer',
    company: 'Petrobras',
    company_legal_name: 'Petróleo Brasileiro S.A.',
    logo: '/images/careers/petrobras-logo.svg',
    location: 'Rio de Janeiro, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2023-07',
    end_date: null,
    industry: 'Energia',
    link: 'https://petrobras.com.br/',
    responsibilities: [
      'Desenvolvimento de aplicações para perfuração de poços utilizando Django, Docker e AWS.',
      'Colaboração com equipes multidisciplinares para otimizar processos e garantir a integridade dos dados.',
    ],
  },
  {
    position: 'Chatbot Development Leader',
    company: 'Hero99',
    company_legal_name: 'Hero99',
    logo: '/images/careers/hero99-logo.png',
    location: 'Curitiba, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2022-09',
    end_date: '2023-05',
    industry: 'Tecnologia',
    link: 'https://hero99.com.br/',
    responsibilities: [
      'Liderança no desenvolvimento de chatbots utilizando GCP e Dialogflow para aumentar o engajamento dos usuários.',
      'Implementação de soluções que resultaram em uma comunicação mais eficiente com os clientes.',
    ],
  },
  {
    position: 'Full Stack Developer',
    company: 'NSH Technologies',
    company_legal_name: 'NSH Technologies',
    logo: '/images/careers/nsh-logo.jpeg',
    location: 'São Paulo, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2020-12',
    end_date: '2022-09',
    industry: 'E-commerce',
    link: 'https://nsh-tech.com/',
    responsibilities: [
      'Contribuição ativa em plataformas de e-commerce com Oracle Commerce Cloud (OCC), melhorando a experiência do usuário.',
      'Participação em projetos de otimização de performance e escalabilidade de sistemas.',
    ],
  },
  {
    position: 'Full Stack Developer',
    company: 'Deep Legal Analytics',
    company_legal_name: 'Deep Legal Analytics',
    logo: '/images/careers/deeplegalanalytics-logo.jpeg',
    location: 'São Paulo, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Freelance',
    start_date: '2020-01',
    end_date: '2020-12',
    industry: 'Legal Tech',
    link: 'https://www.deeplegal.com.br/',
    responsibilities: [
      'Desenvolvimento de soluções jurídicas inovadoras utilizando Node.js, React, Elastic Search e Redis.',
      'Criação de ferramentas que facilitaram o acesso e a análise de dados jurídicos complexos.',
    ],
  },
  {
    position: 'Full Stack Developer',
    company: 'Planos Assessoria & Planejamento Tributário',
    company_legal_name: 'Planos Assessoria & Planejamento Tributário',
    logo: '/images/careers/planos-assessoria-logo.jpeg',
    location: 'Água Boa, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2019-06',
    end_date: '2019-12',
    industry: 'Consultoria',
    link: 'https://planosassessoria.com.br/',
    responsibilities: [
      'Desenvolvimento de aplicações web e mobile utilizando tecnologias modernas como Node.js e React.js.',
      'Colaboração em projetos de desenvolvimento ágil, focando na entrega contínua e melhorias incrementais.',
    ],
  },
]
