import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Software Engineer',
    company: 'Petrobras (via consulting)',
    company_legal_name: 'Petrobras S.A.',
    logo: '/images/careers/petrobras.png',
    location: 'Remote, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2023-07',
    end_date: null,
    industry: 'oil-gas',
    link: 'https://petrobras.com.br',
    responsibilities: [
      'Migrated legacy Oil & Gas systems by migrating from Python 2.7 to Django 4.2 and Python 3.10',
      'Designed asynchronous workflows with Celery, Redis, RabbitMQ, and AWS SQS',
      'Deployed cloud-native applications using Docker, ECS, and S3',
      'Managed PostgreSQL migrations to AWS RDS and improved infrastructure performance',
    ],
  },
  {
    position: 'Senior Backend Developer',
    company: 'GEN (Fintech Platform)',
    company_legal_name: null,
    logo: '/images/careers/gen.png',
    location: 'Remote, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2022-11',
    end_date: '2023-05',
    industry: 'fintech',
    link: null,
    responsibilities: [
      'Built and maintained microservices using NestJS, PostgreSQL, and Prisma ORM',
      'Migrated critical services from Elixir to NestJS, increasing maintainability and team velocity',
      'Integrated Celcoin API for Pix billing, split payments, and webhook handling',
      'Implemented event-driven architecture using RabbitMQ and AWS SQS',
      'Structured monorepo environment combining backend (NestJS) and frontend (Next.js)',
    ],
  },
  {
    position: 'Full Stack Developer',
    company: 'Hero99',
    company_legal_name: null,
    logo: '/images/careers/hero99.png',
    location: 'Remote, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2021-09',
    end_date: '2022-10',
    industry: 'chatbot-tech',
    link: null,
    responsibilities: [
      'Led chatbot development using Dialogflow and GCP for customer interaction',
      'Built scalable platforms using NestJS, MongoDB, and Next.js',
      'Developed automation flows with WhatsApp integration and API orchestration',
    ],
  },
  {
    position: 'Frontend Developer',
    company: 'NSH Technologies',
    company_legal_name: null,
    logo: '/images/careers/nsh.png',
    location: 'Remote, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2020-01',
    end_date: '2021-08',
    industry: 'ecommerce',
    link: null,
    responsibilities: [
      'Built responsive e-commerce interfaces using HTML, CSS, JavaScript and React.js',
      'Improved user experience with Oracle Commerce Cloud (OCC) customization',
      'Collaborated with backend teams for API consumption and interface consistency',
    ],
  },
  {
    position: 'Full Stack Developer',
    company: 'Deep Legal Analytics',
    company_legal_name: null,
    logo: '/images/careers/deep-legal.png',
    location: 'Remote, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2019-01',
    end_date: '2019-12',
    industry: 'legal-tech',
    link: null,
    responsibilities: [
      'Developed legal tech systems using Node.js, React, ElasticSearch and Redis',
      'Integrated machine learning models for document analysis and automation',
      'Built scalable APIs and data pipelines for legal processing',
    ],
  },
  {
    position: 'Full Stack Developer',
    company: 'Planos Assessoria & Planejamento Tributário',
    company_legal_name: null,
    logo: '/images/careers/planos-assessoria.png',
    location: 'Remote, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2019-01',
    end_date: '2019-12',
    industry: 'legal-tech',
    link: null,
    responsibilities: [
      'Built custom tax and accounting platforms using PHP, Vue.js, and PostgreSQL',
      'Optimized tax planning workflows with automation and UI improvements',
    ],
  },
];
