// src/common/constant/careers.ts
import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Senior Software Engineer',
    company: 'Petrobras',
    company_legal_name: 'Petróleo Brasileiro S.A.',
    logo: 'https://media.licdn.com/dms/image/v2/C560BAQGhF5S_rZjL-A/company-logo_200_200/company-logo_200_200/0/1631338308976?e=1755734400&v=beta&t=RCuBlDfN3oIaIhRmALUSiZDKagBQMeZMLtcc6qurRdA',
    location: 'Remote, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2023-07',
    end_date: null,
    industry: 'oil-gas',
    link: 'https://petrobras.com.br',
    responsibilities: [
      'Modernizing mission-critical Oil & Gas simulation platforms used by engineering teams.',
      'Upgraded legacy systems from Python 2.7 to Django 4.2, reducing tech debt and improving stability.',
      'Designed and operated event-driven workflows using Celery, RabbitMQ, Redis and AWS SQS with zero downtime.',
      'Containerized services with Docker and deployed to AWS ECS/RDS, cutting deployment time by ~60%.',
      'Implemented monitoring, health checks and CI/CD pipelines with GitHub Actions for safer releases.',
    ],
  },
  {
    position: 'Senior Backend Developer',
    company: 'GEN (Fintech Platform)',
    company_legal_name: 'General Shopping e Outlets do Brasil S/A',
    logo: 'https://media.licdn.com/dms/image/v2/D4D0BAQEcWB2d0_aAhA/company-logo_200_200/B4DZXYnepbGkAI-/0/1743095983334/sejagen_logo?e=1755734400&v=beta&t=dcVjrxCofdvW-15NEtGRRbAIJqIaxQVzzg8zBQBQapk',
    location: 'Remote, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2022-11',
    end_date: '2023-05',
    industry: 'fintech',
    link: 'https://www.generalshopping.com.br/',
    responsibilities: [
      'Developed BolePix, a Pix billing platform with automated PDFs, split payments and webhook processing.',
      'Rewrote critical services from Elixir to NestJS, improving maintainability and deployment speed.',
      'Designed microservices using NestJS, Prisma and PostgreSQL following Clean Architecture and DDD.',
      'Implemented asynchronous pipelines using RabbitMQ and AWS SQS for high-volume financial operations.',
      'Contributed to a monorepo setup combining backend (NestJS) and frontend (Next.js) services.',
    ],
  },
  {
    position: 'Backend Specialist',
    company: 'Hero99',
    company_legal_name: null,
    logo: 'https://media.licdn.com/dms/image/v2/D4D0BAQHKh3Jupd9ZLA/company-logo_200_200/company-logo_200_200/0/1714395700907/hero99_logo?e=1755734400&v=beta&t=KY2-9v3xW1RitpcG8e02FOrcMX6hw6mcpE-RIbq9d58',
    location: 'Remote, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2021-09',
    end_date: '2022-10',
    industry: 'conversational-ai',
    link: 'http://hero99.com.br/',
    responsibilities: [
      'Led backend development of a conversational platform for healthcare and education clients.',
      'Built real-time messaging pipelines using Node.js, RabbitMQ and Dialogflow for automated triage and support.',
      'Implemented multi-tenant backend services with NestJS and MongoDB to support growing client bases.',
      'Delivered dashboards and internal automation tools to improve operations and visibility.',
    ],
  },
  // Se você quiser manter um card de carreira inicial, pode criar algo compacto como abaixo:
  {
    position: 'Early Career — Full-Stack & Internal Tools',
    company: 'Multiple companies (LegalTech, e-commerce, consulting)',
    company_legal_name: null,
    logo: '',
    location: 'Remote, Brazil 🇧🇷',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2018-01',
    end_date: '2021-07',
    industry: 'software',
    link: '',
    responsibilities: [
      'Built LegalTech dashboards with Node.js, React, Redis and ElasticSearch.',
      'Developed e-commerce frontends on Oracle Commerce Cloud with React and API integrations.',
      'Created internal tax and accounting tools using PHP, Vue.js and PostgreSQL.',
    ],
  },
];
